web:
  build: .
  command: 'bash -c ''bin/reed'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8000
  ports:
    - '8000:8000'
  volumes:
    - '.:/app/user'
